module.exports = {
    blocks: {
        number: { Name: "number", Type:  "BigInteger"},
        hash: { Name: "hash", Type: "String"},
        parent_hash: { Name: "parent_hash", Type: "String"},
        nonce: { Name: "nonce", Type: 'String'},
        sha3_uncles: { Name: "sha3_uncles", Type: 'String'},
        logs_bloom: { Name: "logs_bloom", Type: 'String'},
        transactions_root: { Name: "transactions_root", Type: 'String'},
        state_root: { Name: "state_root", Type: 'String'},
        receipts_root: { Name: "receipts_root", Type: 'String'},
        miner: { Name: "miner", Type: 'String'},
        difficulty: { Name: "difficulty", Type: "DECIMAL(38,0)"},
        total_difficulty: { Name: "total_difficulty", Type: "DECIMAL(38,0)"},
        size: { Name: "size", Type: "BigInteger"},
        extra_data: { Name: "extra_data", Type: "String"},
        gas_limit: { Name: "gas_limit", Type: "BigInteger"},
        gas_used: { Name: "gas_used", Type: "BigInteger"},
        timestamp: { Name: "timestamp", Type: "TIMESTAMP"},
        transaction_count: { Name: "transaction_count", Type: "BigInteger"},
        base_fee_per_gas: { Name: "base_fee_per_gas", Type: "BigInteger"}
      },
      transactions: {
        hash: { Name: 'hash', Type: 'String'},
        nonce: { Name: 'nonce', Type: 'BigInteger'},
        transaction_index: { Name: 'transaction_index', Type: 'BigInteger'},
        from_address: { Name: 'from_address', Type: 'String'},
        to_address: { Name: 'to_address', Type: 'String'},
        value: { Name: 'value', Type: 'Numeric(38)'},
        gas: { Name: 'gas', Type: 'BigInteger'},
        gas_price: { Name: 'gas_price', Type: 'BigInteger'},
        input: { Name: 'input', Type: 'String'},
        receipt_cumulative_gas_used: { Name: 'receipt_cumulative_gas_used', Type: 'BigInteger'},
        receipt_gas_used: { Name: 'receipt_gas_used', Type: 'BigInteger'},
        receipt_contract_address: { Name: 'receipt_contract_address', Type: 'String'},
        receipt_root: { Name: 'receipt_root', Type: 'String'},
        receipt_status: { Name: 'receipt_status', Type: 'BigInteger'},
        block_timestamp: { Name: 'block_timestamp', Type: 'TIMESTAMP'},
        block_number: { Name: 'block_number', Type: 'BigInteger'},
        block_hash: { Name: 'block_hash', Type: 'String'},
        max_fee_per_gas: { Name: 'max_fee_per_gas', Type: 'BigInteger'},
        max_priority_fee_per_gas: { Name: 'max_priority_fee_per_gas', Type: 'BigInteger'},
        transaction_type: { Name: 'transaction_type', Type: 'BigInteger'},
        receipt_effective_gas_price: { Name: 'receipt_effective_gas_price', Type: 'BigInteger'},
        receipt_l1_fee: { Name: 'receipt_l1_fee', Type: 'BigInteger'},
        receipt_l1_gas_used: { Name: 'receipt_l1_gas_used', Type: 'BigInteger'},
        receipt_l1_gas_price: { Name: 'receipt_l1_gas_price', Type: 'BigInteger'},
        receipt_l1_fee_scalar: { Name: 'receipt_l1_fee_scalar', Type: 'Float'},
      },
}